version: "3.9"

services:
  blog_database:
    image: postgres:15
    hostname: ${DB_HOST}
    container_name: blog_database_container
    command: -p ${DB_PORT}
    restart: on-failure
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
    volumes:
      - ./data/blog/postgres:/var/lib/postgresql/data
    networks:
      - main

networks:
  main:

volumes:
  data:
