version: "3.9"

services:
  postgres:
    image: postgres
    container_name: postgres_container
    hostname: ${BLOG_DB_HOST}
    command: -p ${BLOG_DB_PORT}
    environment:
      POSTGRES_USER: ${BLOG_DB_USER}
      POSTGRES_PASSWORD: ${BLOG_DB_PASSWORD}
      POSTGRES_DB: ${BLOG_DB_NAME}
      PGDATA: /data/postgres
    volumes:
      - ./data/blog/postgres:/var/lib/postgresql/data
    networks:
      - blog_main
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - /data/blog/pgadmin:/var/lib/pgadmin/data
    ports:
      - ${PG_ADMIN_PORT}:80
    networks:
      - blog_main
    restart: unless-stopped
    depends_on:
      - postgres

networks:
  blog_main:

volumes:
  data:
