version: "3.9"

services:
  postgres:
    image: postgres
    container_name: postgres_container
    hostname: ${BLOG_DB_HOST}
    command: -p ${BLOG_DB_PORT}
    environment:
      POSTGRES_USER: ${BLOG_DB_USER}
      POSTGRES_PASSWORD: ${BLOG_DB_PASSWORD}
      POSTGRES_DB: ${BLOG_DB_NAME}
      PGDATA: /data/postgres
    volumes:
      - ./data/blog/postgres:/var/lib/postgresql/data
    ports:
      - ${BLOG_DB_PORT}:${BLOG_DB_PORT}
    networks:
      - blog_main
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - /data/blog/pgadmin:/var/lib/pgadmin/data
    ports:
      - ${PG_ADMIN_PORT}:80
    networks:
      - blog_main
    restart: unless-stopped
    depends_on:
      - postgres

  redis:
    container_name: ${REDIS_HOST}
    hostname: ${REDIS_HOST}
    image: redis:latest
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
    volumes:
      - ./redis.conf:/usr/local/etc/redis.conf
    networks:
      - blog_main

  seq:
    image: datalust/seq:latest
    container_name: seq_project_container
    hostname: ${SEQ_HOST}
    ports:
      - ${SEQ_PORT}:80
    environment:
      ACCEPT_EULA: "Y"
    volumes:
      - ./data/project/seq:/data
    networks:
      - blog_main
    restart: unless-stopped

networks:
  blog_main:

volumes:
  data:
